### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by getintouchapp** [reinterpretcat/utymap#102]
On the linux build there are some modifications that has be done to the build instructions.

For Ubuntu 16.10 the libboost library is referenced by another name than the one mentioned in wiki

 `cp shared/libUtyMapLib.so ../../unity/Assets/Plugins/libUtyMap.Shared.so`

should be

`cp shared/libUtyMapLib.Shared.so ../../unity/Assets/Plugins/libUtyMap.Shared.so`

Copy the plugin folder should be from base (not mentioned) to demo directory (wiki is copying to non-existing directory)

Can you enable wiki permissions to all so we can contribute to this too?

Thanks!
Ganesh

**Comment by reinterpretcat** [comment]
Hi Ganesh! Thanks for reporting this. I forgot to update linux wiki after I renamed library. Will fix it.

Regarding contribution, there is ability to checkout wiki pages. I believe that it is possible to create pull request then which I can review before it is applied. I don't want just to enable write access to everyone as it will be difficult to track changes.

**Comment by reinterpretcat** [comment]
Close as answered
