### ISSUE TITLE
hi unable to hide console and password require to expot

### ISSUE THREAD

**Issue by erafilms** [reinterpretcat/utymap#105]
i am using it on android , i says sign in password required , and also the character is not moving in android and please let me know how to hide console

**Comment by reinterpretcat** [comment]
Hi, debug console can be hidden if you set the corresponding flag in ApplicationManager class:

https://github.com/reinterpretcat/utymap/blob/master/unity/demo/Assets/Scripts/ApplicationManager.cs
public void CreateDebugConsole(bool isOpen = true)

> i says sign in password required

Didn't get it: can you provide more details?

> also the character is not moving in android

Have you enabled Mobile input?

**Comment by erafilms** [comment]
thanks my problem is resolved
