### ISSUE TITLE
UtyMap.Shared.dll is not found

### ISSUE THREAD

**Issue by soorajkbabu** [reinterpretcat/utymap#115]
Hi, 
Thanks to the wonderful work. I tried running the unity file but getting an error like DllNotFoundException: UtyMap.Shared
I tried a lot to fix the error. But Could not make it. Can someone help?
Thanks.

**Comment by reinterpretcat** [comment]
This is native library, have you built it? Please see OS specific instructions here:
https://github.com/reinterpretcat/utymap/wiki

If you're using Windows, you can use library from the latest release (see release page)

**Comment by reinterpretcat** [comment]
Closed as invalid
