### ISSUE TITLE
Zooming in demo app causes out of bounds error [MAC]

### ISSUE THREAD

**Issue by nextpulse** [reinterpretcat/utymap#116]
On a build on mac. Running the demo and zoom in. At appox zoom = 2.22, following is thrown:

Mesh.uv3 is out of bounds. The supplied array needs to be the same size as the Mesh.vertices array.
UnityEngine.UI.Text:OnPopulateMesh(VertexHelper)
Assets.Scripts.UI.SphereText:OnPopulateMesh(VertexHelper) (at Assets/Scripts/UI/SphereText.cs:16)
UnityEngine.Canvas:SendWillRenderCanvases()

<img width="1073" alt="screenshot_870" src="https://user-images.githubusercontent.com/2224986/26943382-3777b2d4-4c3a-11e7-8b82-464dae600564.png">

**Comment by nextpulse** [comment]
Another way to reproduce this bug is to start the demo with map behavior->zoom > 3

**Comment by reinterpretcat** [comment]
which version are you using? the latest from master or release?

**Comment by nextpulse** [comment]
The latest (June 6th commits) from master.

**Comment by reinterpretcat** [comment]
I can see error message after I've updated unity to 5.6.0f3. It is unity bug:

https://issuetracker.unity3d.com/issues/vertexhelper-dot-adduivertextrianglestream-method-throws-mesh-dot-uv3-is-out-of-bounds-error

However, in my case tiles are loaded, so the bug does not affect functionality. I'm closing issue as it is not utymap related.

**Comment by reinterpretcat** [comment]
I've applied suggested workaround: https://github.com/reinterpretcat/utymap/commit/4410496ca3ddc8df1f1238881e58338acc4b09bb

So, the error is gone. It will be merged later in master once I've finished current feature I'm working on.
