### ISSUE TITLE
Is there a 64bit version of the Utymap.Share library?

### ISSUE THREAD

**Issue by bohuang3d** [reinterpretcat/utymap#120]
The one from the release doesn't work on my machine I think it's x86? Unity does not recognize it no matter what

**Comment by reinterpretcat** [comment]
I'm using only x64 version, so it is included in release artifacts. If you have problems, you can try to build your own version

**Comment by bohuang3d** [comment]
Hmm, still I keep on getting in Unity:
Failed to load 'Assets/Plugins/UtyMap.Shared.dll' with error 'The specified module could not be found.

Even though as you can see the dll is at the proper place:
![utymap_shared](https://user-images.githubusercontent.com/5192187/30504526-23b1e174-9a24-11e7-8297-c2cf9cedb13c.JPG)

I tried building myself but run into boost cannot find certain libraries errors. I'm stuck

**Comment by reinterpretcat** [comment]
Shared lib on windows depends on zlib.dll, have you copied it too? You might get such error if dependency could not be found.
