### ISSUE TITLE
Crash bug when loading too many tiles

### ISSUE THREAD

**Issue by KingsleyStephens** [reinterpretcat/utymap#121]
Evaluating UtyMap in Unity I am running into a crash bug when loading too many tiles. I am modifying your map demo to use a perspective first person camera and loading tiles that are in the camera frustum.  However there is a persistent crash bug that makes the demo unstable. I am happy to provide my source code modifications if you like.

**Comment by reinterpretcat** [comment]
I saw some crashes once I added mesh caching optimization which can be disabled. However, if it is disabled, then average tile loading time is increased.

I think the issue can be reproduced with existing Map scene, but it would be nice to have some demo scene with first person camera. Could you please create a pull request?

**Comment by KingsleyStephens** [comment]
I have created a branch off your master and created a demo that reproduces
the bug. I have just started using GitHub so am unfamiliar with how to
create a pull request. I am assuming I will need to be a member of your
repository to push my branch, after which I can then create the pull
request?

**Comment by reinterpretcat** [comment]
No, you don't need to be a member: you submit it and then I review it. Check instructions here: https://help.github.com/articles/creating-a-pull-request/

**Comment by reinterpretcat** [comment]
Please check ThirdPerson scene: I did some changes in core library, it seems a little bit more stable now

**Comment by KingsleyStephens** [comment]
Thank you for your update. It looks like we will be using MapBox for this
particular project now.
