### ISSUE TITLE
Project Export & Unity Build APK Issue

### ISSUE THREAD

**Issue by subhechhu** [reinterpretcat/utymap#126]
I tried building an apk with the demo application via unity.
When I build the apk, the map doesn't load and I can see an error which say

> **Unable to find UtyMap.Shared**

every single time & the object free fall to infinity. Poor Guy.
Also, I am not being able to export the Unity-based project to Android. It fails every time.

Would be great if I could get some help regarding the subject.
Thanks

**Comment by reinterpretcat** [comment]
Have you built UtyMap.Shared as it is described here: https://github.com/reinterpretcat/utymap/blob/master/docs/build.md
?

**Comment by subhechhu** [comment]
Yeah. I built it on Mac and followed the same procedure as given. It works with unity. I can run the project. 
I can create an apk with Unity & run it on an Android device too. But when it runs on the device, the map doesn't load and 3D object in **ThirdPerson** scene keeps falling and log on the device says unable to find UtyMap.Shared.

**Comment by reinterpretcat** [comment]
If you followed instructions for android build (armeabi-v7a, NDK, etc), then it is hard to say what is wrong..

**Comment by subhechhu** [comment]
If I create a Unity project and try to build an apk or try to export the project to Android project as Unity allows to do that, will that work or I will have to build project for Android as in the given link?

**Comment by subhechhu** [comment]
Finally So is generated. 
I will try to build it again now.
Thanks :)
