### ISSUE TITLE
Unable to load model errors

### ISSUE THREAD

**Issue by lmbarns** [reinterpretcat/utymap#132]
I'm running it in the Unity 2018.3 editor and it's mostly great but seems like once it hits one failed building it triggers a swath of them, and I'm trying to track it down even if just to add a try catch statement or some way to fail gracefully.  The terrain loads great, but they're mostly empty after it gets stuck.

[Error] model.loader:Unable to load model: Area[367189587]:tags:{addr:city:Portland,addr:housenumber:7823,addr:postcode:97217,addr:street:North Albina Avenue,building:detached,building:levels:2,ele:27.3,} closed. Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

**Comment by reinterpretcat** [comment]
Looks like this building requires some changes in mapcss rules and theoretically can be fixed by missing rule. I would recommend to check full stack trace.

**Comment by lmbarns** [comment]
Thank you, was trying to figure out where to edit, there are a lot of files.  It's an amazing project!
