### ISSUE TITLE
Issues when trying to install and after built

### ISSUE THREAD

**Issue by realwindz** [reinterpretcat/utymap#45]
Hey. I was trying to use your project in my game. Really finding for a dynamic 3D real world map library. 

When I was trying to install it, the cmake kept saying that can not find the boost_unit_test library. Then I just added the use boost static library as true. But then I could not build it. The project failed to be built, the error is can not find boost_unit_test-gt-120vs-mt.lib. I really didn`t know why. Then I tried to build the whold project without the "test" project, but it can not generate the utymaplib.dll.  But I can still build the unity project and make it run. 
This time, the unity project worked but no map shown. Really weird.

By the way, is there any library/apis I can use for real-world dynamic 3D maps building ? I need it has the 3d models returned instead of some depth image. 

Thanks a lot.

**Comment by reinterpretcat** [comment]
Hi, for such issues I have created gitter chat: https://gitter.im/reinterpretcat/utymap 

Let's discuss there.

Short notes:
- In general, you don't need to build tests.
- Recently, I renamed utymaplib to UtyMap.Shared, just updated docs.
