### ISSUE TITLE
CI: cannot execute mozroots command

### ISSUE THREAD

**Issue by reinterpretcat** [reinterpretcat/utymap#46]
This command is required by mono and NuGet to restore packages. However it fails due to the problem with mozilla server:

http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1

**Comment by edmorley** [comment]
Mozilla's MXR site is likely not coming back (see https://bugzilla.mozilla.org/show_bug.cgi?id=1279952).

However it's worth noting that it should never have been used to pull from as part of a build/automation anyway - it's a code indexer, not a source code repository. (And particularly not over plain HTTP!)

Though this need to be fixed upstream in mozroots, wherever that is.

**Comment by reinterpretcat** [comment]
Thanks for information.

I tried with defining another url:

 mozroots --import --sync --url https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt

It works on travis docker image I have locally on my laptop, but fails remotely. Don't have idea why.

So far, I'm considering remove mozroots and NuGet from setup and commit needed binaries (nunit and moq). Don't like this approach, but I want to make CI working.

**Comment by reinterpretcat** [comment]
Commited binaries to repository and removed NuGet
