### ISSUE TITLE
Generate 3d models from map data

### ISSUE THREAD

**Issue by plandem** [reinterpretcat/utymap#91]
is it possible to use core to create some kind of toolchain?! i.e. generate .obj files(3d models) of buildings? It's not clear how to use, some examples would be nice.

**Comment by reinterpretcat** [comment]
Yes, it is possible. The main question is how API should look like? For example:
* store all buildings for given area/tile as separate models
* store buildings by id
* should be it a part of core library or unity?

Also some buildings consist of multiple parts which are not parts of one relation. It means that you will have them stored separately.

In general, you can already implement this using current API: when tile is loaded, it emits TileLoadFinishMessage which aggregates Tile object. Tile holds a reference to GameObject which is parent of all rendered objects for loaded quadkey. You can iterate through all its children and find buildings using game object name: all buildings start from "building:" following id.

**Comment by reinterpretcat** [comment]
Closed as answered
